# #############################################################################
# Copyright (c) 2022,2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################
---
{{- $fullName := include "dataprovider.fullname" . -}}
{{- if .Values.seedTestdata }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-post-install-testdata
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation #,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ $fullName }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "python:3.11"
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "{{- cat "/opt/scripts/upload-data.sh" (include "submodelservers.host" .) (include "registry.url" .) (include "edc.controlplane.host" .) (include "edc.dataplane.host" .) (include "edc.key" .) (include "edc.bpn" .) }}"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/scripts
      volumes:
        - name: config-volume
          {{- if .Values.testdataConfigMap }}
          configMap:
            name: {{ .Values.testdataConfigMap }}
            defaultMode: 0777
          {{- else }}
          configMap:
            name: {{ $fullName }}-postinstall-configmap
            defaultMode: 0777
          {{- end }}
{{- end }}