

apiVersion: v2
name: tx-data-provider
description: A Helm chart for Kubernetes

type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: digital-twin-registry
    version: 0.4.1
    repository: https://eclipse-tractusx.github.io/sldt-digital-twin-registry
  - name: submodelservers
    repository: file://../submodelservers
    version: 0.1.0
  - name: tractusx-connector
    repository: https://eclipse-tractusx.github.io/tractusx-edc
    version: 0.5.3
  - name: postgresql
    alias: edc-postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.12.10
