name: IRS DEV Cucumber Integration test execution

on:
  workflow_dispatch: # Trigger manually
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'charts/**'
      - '.config/**'
      - 'docs/**'
      - 'local/**'
      - 'irs-load-tests/**'

# Cancel previous Test executions if a new one is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-integration-test:
    uses: ./.github/workflows/xray-cucumber-integration.yaml
    secrets:
      oauth2TokenUrl: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI }}
      clientId: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_ID }}
      clientSecret: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_SECRET }}
      jiraUser: ${{ secrets.ORG_IRS_JIRA_USERNAME }}
      jiraPassword: ${{ secrets.ORG_IRS_JIRA_PASSWORD }}
    with:
      executionFilter: "not @Ignore and @INTEGRATION_TEST and @DEV"
      exportFilter: "11349"
